version: "3.9"
services:
  # web:
  #   depends_on:
  #     - postgres_db
  #   build:
  #     context: ./web
  #     dockerfile: Dockerfile
  #   image: django-k8s:v1
  #   environment:
  #    - PORT=8020
  #   env_file:
  #     - web/.env
  #   ports:
  #   # map local port 8001 to Docker port 8020
  #     - "8001:8020"
  #   command: sh -c "chmod +x /app/migrate.sh && sh /app/migrate.sh && /app/entrypoint.sh"
  postgres_db:
    image: postgres
    restart: always
    command: -p 5433
    env_file:
      - web/.env
    expose:
      - 5433
    ports:
      - "5433:5433"
    volumes:
     # map our persistent volume to the temporary postgresql data
      - postgres_data:/var/lib/postgresql/data/

# define a persistent volume
volumes:
  postgres_data: